// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RAS.Bootcamp.mvc.Models;

#nullable disable

namespace RAS.Bootcamp.mvc.Models.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221016000226_ContentDb")]
    partial class ContentDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RAS.Bootcamp.mvc.Models.Entities.Barang", b =>
                {
                    b.Property<int>("IdBarang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBarang"));

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("Harga")
                        .HasColumnType("numeric");

                    b.Property<int>("IdPenjual")
                        .HasColumnType("integer");

                    b.Property<string>("Nama")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("stok")
                        .HasColumnType("integer");

                    b.HasKey("IdBarang");

                    b.HasIndex("IdPenjual");

                    b.ToTable("Barang");
                });

            modelBuilder.Entity("RAS.Bootcamp.mvc.Models.Entities.Pembeli", b =>
                {
                    b.Property<int>("IdPembeli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPembeli"));

                    b.Property<string>("Alamat")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<string>("Nama")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("No_HandPhone")
                        .HasColumnType("text");

                    b.HasKey("IdPembeli");

                    b.HasIndex("IdUser");

                    b.ToTable("Pembelies");
                });

            modelBuilder.Entity("RAS.Bootcamp.mvc.Models.Entities.Penjual", b =>
                {
                    b.Property<int>("IdPenjual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPenjual"));

                    b.Property<string>("Alamat")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<string>("Nama_Toko")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdPenjual");

                    b.HasIndex("IdUser");

                    b.ToTable("Penjual");
                });

            modelBuilder.Entity("RAS.Bootcamp.mvc.Models.Entities.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUser"));

                    b.Property<int>("NoHandPhone")
                        .HasMaxLength(20)
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("tipe")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdUser");

                    b.ToTable("User");
                });

            modelBuilder.Entity("RAS.Bootcamp.mvc.Models.Entities.Barang", b =>
                {
                    b.HasOne("RAS.Bootcamp.mvc.Models.Entities.Penjual", "Penjual")
                        .WithMany("Barang")
                        .HasForeignKey("IdPenjual")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Penjual");
                });

            modelBuilder.Entity("RAS.Bootcamp.mvc.Models.Entities.Pembeli", b =>
                {
                    b.HasOne("RAS.Bootcamp.mvc.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RAS.Bootcamp.mvc.Models.Entities.Penjual", b =>
                {
                    b.HasOne("RAS.Bootcamp.mvc.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RAS.Bootcamp.mvc.Models.Entities.Penjual", b =>
                {
                    b.Navigation("Barang");
                });
#pragma warning restore 612, 618
        }
    }
}
